POST http://localhost:3001/api/users
Content-Type: application/json

{
  "Password": "hxsapntsy",
  "First Name": "João Gabriel",
  "Last Name": "Senger",
  "Email": "joão_gabriel.senger@email.com",
  "Age": 18
}