POST http://localhost:3001/api/users
Content-Type: application/json

{
  "password": "hxsapntsy",
  "first_name": "João Gabriel",
  "last_name": "Senger",
  "email": "joão_gabriel.senger@email.com",
  "age": 18
}